### ISSUE TITLE
Uncaught error fetching from discord API

### ISSUE THREAD

**Issue by dqbert** [dqbert/buttbot#68]
[Tue Apr 13 2021 07:00:30] Got uncaught error:
[Tue Apr 13 2021 07:00:30] HTTPError [FetchError]: request to https://discord.com/api/v7/gateway/bot failed, reason: getaddrinfo EAI_AGAIN discord.com
[Tue Apr 13 2021 07:00:30]     at RequestHandler.execute (/home/buttbot-host/buttbot/node_modules/discord.js/src/rest/RequestHandler.js:93:15)
[Tue Apr 13 2021 07:00:30]     at processTicksAndRejections (node:internal/process/task_queues:94:5)
[Tue Apr 13 2021 07:00:30]     at RequestHandler.push (/home/buttbot-host/buttbot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
[Tue Apr 13 2021 07:00:30]     at WebSocketManager.connect (/home/buttbot-host/buttbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:138:9)
[Tue Apr 13 2021 07:00:30]     at Client.login (/home/buttbot-host/buttbot/node_modules/discord.js/src/client/Client.js:223:7) {
[Tue Apr 13 2021 07:00:30]   code: 500,
[Tue Apr 13 2021 07:00:30]   method: 'get',
[Tue Apr 13 2021 07:00:30]   path: '/gateway/bot'
[Tue Apr 13 2021 07:00:30] }

**Comment by dqbert** [comment]
This hangs up the bot entirely.
